### ISSUE TITLE
The legal status of your code?

### ISSUE THREAD

**Issue by NickViz** [JesperMikkelsen/Big-Numbers#1]
Hello,

is your code publicly available? If so - what is the license?

thanks in advance,
Nikolai

**Comment by JesperMikkelsen** [comment]
Hi

You can take it as it is, and do with it whatever you like :-)

Regards
Jesper

2016-09-26 11:56 GMT+02:00 NickViz <notifications@github.com>:

**Comment by NickViz** [comment]
Thanks Jesper!

it would be nice if you add a license file at least to your repository root (when you have time of course).
I would advice you the MIT license https://opensource.org/licenses/MIT :-) but sure it's your right to use any license that suits you the most.

Nikolai

**Comment by JesperMikkelsen** [comment]
Thanks for the advice. Maybe a silly question: Why is it better to have a license than no lincense at all?
Jesper

**Comment by NickViz** [comment]
Hello Jesper,

well, having license you explicitly state that your code is available (at certain conditions) for some/anybody. I guess 99.9% of non-private developers is not going to use a code that doesn't clearly state that they can use it. It's like you see a opened cookie box in the shop - you are not going to take it with you just because it's opened. However if that cookies is accomplished with a label - "for free/probe it/take it" - you enjoy by it.

Briefly speaking - if you want that somebody else benefits from your work - label it with appropriate license. If you don't mind at all - know that less people can use your code.

Nikolai

**Comment by JesperMikkelsen** [comment]
Thanks.. Good answer. I'll try to come up with some kind of text, perhaps the one you suggested. The problem is that some of the folders contain software with its own term of use. (ex. a very old version of paintlib, used to save/load images as jpg,png,tiff files) - the license in that subfolder should of cause be used instead of mine. Damn, its complicated!! Actually I've only put my lib to github, so that some specific files (written by me) would be available from Stackoverflow. and the links there shows that they can be used by everyone, which implies, I guess, it's not worth spend too much time to think up a license for the whole lib. But thanks anyway.
Jesper

**Comment by JesperMikkelsen** [comment]
Hi Nikolai

I did it....Now there is a readme-file in my repositiory
Regards
Jesper
