### ISSUE TITLE
License for file Lib/Src/Math/Int128x64.asm

### ISSUE THREAD

**Issue by cpsusie** [JesperMikkelsen/Big-Numbers#3]
Mr Mikkelsen,

     What is the status of your copyright / licensing for referenced file?  I am working on a 128-bit cross platform unsigned 128-bit integer library with taking full advantage of C++20 features.  I would like to use your code for division / modulus when compiling for x64 windows in the case that the division / modulus is not constant evaluated.  I can't find any license or copyright for this code.  I plan on licensing my library under the MIT license, so, to use your very nice code, I'd need to see you license it under a compatible license.  I sure would like to use it though.  Thank you!

Chris Susie

**Comment by JesperMikkelsen** [comment]
I will add a license asap
Jesper

søn. d. 20. dec. 2020 21.07 skrev Christopher Susie <
notifications@github.com>:

**Comment by cpsusie** [comment]
Thank you!

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by JesperMikkelsen** [comment]
Its ready for you.
What an honor.. 😏

søn. d. 20. dec. 2020 21.15 skrev Christopher Susie <
notifications@github.com>:

**Comment by cpsusie** [comment]
The honor, sir, is mine. :)

**Comment by robokid1888** [comment]
Hi Chris
Yesterday you asked me to add a copyright / license to the file int128.asm, because you want to use it as part in a library lincensed  under the MIT license. And I quickly added a copyright I comment, as free software.
Im not an expert in copyrights and lincensing, actually I know nothing about it.
And today, just 2 hours ago, I realised, that there is in fact a copyright from Microsoft (All rights reserved) on this code.
Originally I got the code from a debug-session several years ago, simply by copying the text from disassembler window into the editor and modified it to fit x64-code. And at that time, it didn't show any copyrights/license. I didn't know, that there was a lincense until today.
I've deleted the file from my github-repository until I find what's the correct license (if any)
Jesper

**Comment by cpsusie** [comment]
Makes sense.  I will probably avoid using it then.  Maybe I could do the same thing you did but with clang and just adjust adjust syntax from at&t to Microsoft.  Let me know if you ever hear from Microsoft about it.  If I can figure it out with clang I'll let you know.



Sent from my Verizon, Samsung Galaxy smartphone



-------- Original message --------
